endpoint: https://jira.talendforge.org
user: emmanuel_g
password-source: gopass
password-name: Work/Jira/emmanuel_g

project: TDI

custom-commands:
  - name: print-project
    help: print the name of the configured project
    script: "echo $JIRA_PROJECT"

  - name: mine
    help: display issues that are/was assigned to me
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          {{jira}} list -s updated --template rofi-list --query "resolution = unresolved and (assignee=currentuser() OR assignee was currentUser() OR reporter = currentUser()) and project = $JIRA_PROJECT ORDER BY updated desc, priority"
      else
          # otherwise list issues for all project
          {{jira}} list --template table --query "resolution = unresolved and assignee=currentuser() ORDER BY priority asc, created"
      fi

  - name: sprint
    help: display issues for active sprint
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          {{jira}} list --template table --query "sprint in openSprints() and type != epic and resolution = unresolved and project=$JIRA_PROJECT ORDER BY rank asc, created"
      else
          # otherwise list issues for all project
          echo "\"project: ...\" configuration missing from .jira.d/config.yml"
      fi

  - name: assigned2me
    help: display issues assigned to me
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          {{jira}} list -s updated --template rofi-list --query "resolution = unresolved and assignee=currentuser() ORDER BY updated desc, priority"
      else
          # otherwise list issues for all project
          {{jira}} list --template table --query "resolution = unresolved and assignee=currentuser() ORDER BY priority asc, created"
      fi
