#!/bin/sh

url=${1:-$QUTE_URL}
qualities=$(youtube-dl --list-formats "$url")

if [ $? != 0 ]; then
	printf 'message-error "Unsupported URL: %s"' "$url" >>"$QUTE_FIFO"
	exit
fi

quality=$({
	printf 'best\nbestvideo\nbestaudio\n'
	printf '%s\n' "$qualities" | grep '^[[:digit:]]' | tac
} | rofi -dmenu -l 10 -p 'quality ')

if [ $? != 0 ]; then
	exit
fi
title=`echo $QUTE_TITLE | sed -e 's/\//-/; s/ - YouTube//' `
quality=$(printf '%s' "$quality" | awk '{ print $1 }')
extension=$(printf '%s' "$quality" | awk '{ $2 ? e=$2 : e="mp4"; print e; }')
command=`printf 'download -d "~/Downloads/%s.%s" %s\n' "$title" "$extension" "$(youtube-dl --get-url --format "$quality" "$url")"`
#echo $command >> ~/.xsession-errors
echo $command >> "$QUTE_FIFO"

